sonar.projectKey=my-django-app
sonar.organization=my-org
sonar.host.url=https://sonarcloud.io
sonar.login=sqa_6dc1802b53efc9fa1bf105569215bb08d7ede826

# Source files
sonar.sources=.

# Exclude virtual env, migrations, etc.
sonar.exclusions=venv/**,**/migrations/**,**/__pycache__/**

# Python-specific settings
sonar.python.coverage.reportPaths=coverage.xml